DE-7548 | Handle not-IAM users
Wikia/athena_alerter pull request #9
Opened 2023-06-29 10:30 UTC by JackThePie

## Description
not-IAM useres (provided by AssumedRoles) do not have `userName`, so the function is failing.

2023-07-02 18:53 UTC, k-nrad approved these changes

2023-07-07 18:40 UTC, MikolajBalcerek requested changes
`cf.yaml` is intended as a template for users of this open-source project outside of Fandom :).

Can you apply your changes from https://github.com/Wikia/crossbow/pull/3038/files into this `cf.yaml` and not remove it?

2023-07-10 09:26 UTC, JackThePie commented
Well, but this fix does not break the current usage and IMO should be applied in the repo as a fix, not only in crossbow. What do you think, @MikolajBalcerek ?

2023-07-10 11:54 UTC, MikolajBalcerek approved these changes

2023-07-10 11:58 UTC, merged